name: go-test
on: [push]
permissions:
  contents: read
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.17'
          cache: false
      - uses: actions/checkout@v3
      - name: test
        run: |
          go test -v ./...
